[package]
name = "Release-Monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.92"
clap = { version = "4.6.6", features = ["derive"] }
reqwest = { version = "0.13.4", features = ["json"] }
rusqlite = "0.40.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_yaml = "0.9.34"
tokio = { version = "1.53.1", features = ["rt", "rt-multi-thread", "macros"] }
log = "0.4.33"
