# Usage:
#refresh_interval: 3600                                 # Refresh interval in seconds. Describes refresh rate of requests to remote repository on Github
#
#repositories:                                          # Describes a list of repositories to be monitored
#  - name: netbird                                      # Starting with name and owner of a repo (Example: https://github.com/netbirdio/netbird, https://github.com/<owner>/<name>)
#    owner: netbirdio
#
#    on_release: |                                      # Describes a banch of cammands to be executed when detecting new release
#      echo "New release detected for example-repo!"
#      echo "Current version: {{ current_version }}"
#      echo "New version: {{ new_version }}"
#      # Add your custom script logic here

refresh_interval: 3600

repositories: []